%YAML:1.0

inputImages: ./images/foobar
outputImages: ./images/foobar

capturedImagesRectified: ./images/demo

capturedDisparities: ./images/disparityMaps

outputParameter: ./parameters/foobar
inputParameter: ./parameters/baseline_small
