%YAML:1.0

inputImages: ./images/moritz-test2000
outputImages: ./images/moritz-test2000

capturedImagesRectified: ./images/moritzTest20000

capturedDisparities: ./images/disparityMaps

outputParameter: ./parameters/wide-baseline
inputParameter: ./parameters/wide-baseline
