%YAML:1.0

inputImages: ./images/calibration_new_small_obj
outputImages: ./images/rotation_test

capturedImagesRectified: ./images/rotation_test

capturedDisparities: ./images/disparityMaps

outputParameter: ./parameter/0.13247
inputParameter: ./parameter/newCalibration
